definitions:
  main.User:
    properties:
      age:
        description: '@in body'
        type: integer
      id:
        description: |-
          @in body
          @required
        type: string
      name:
        description: '@in body'
        type: string
    type: object
info:
  contact: {}
paths:
  /users/{id}:
    get:
      description: Retrieves a user from the system based on their ID
      parameters:
      - description: The user's ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.User'
      summary: Get user by ID
      tags:
      - users
swagger: "2.0"
